version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: movegreen_backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./Backend:/app

  db:
    image: postgres:15-alpine
    container_name: movegreen_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
